### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by pilgwon**
In Character Set like Korean, In Example, 레드 goes 레ㄷㅡ and 베이지 goes ㅂㅔㅇㅣㅈㅣ. This bug fixed

### CODE REVIEW

**Comment by kuler90** [comment]
Hi! Your fix looks a bit unclear 😀. Can you mark it with a comment?

**Comment by pilgwon** [comment]
Yes!

I modify this line
```
self.inputTextField.text = [tags lastObject];
```
to
```
if (![_inputTextField.text isEqualToString:tags.lastObject])
    self.inputTextField.text = [tags lastObject];
```

Thanks

**Comment by kuler90** [comment]
I see that in your commit. I meant that you should add comments in your code about reason of these lines and update the PR. I think the fix is a bit tricky and can be unclear without commenting.

Thanks

**Comment by pilgwon** [comment]
Oh so sorry for misunderstood!
In example, If i write `RED` in English, this library clearly writes `RED`. If i write `레드` in korean (this mean red), this library writes `ㄹㅔㄷㅡ`.
I don't know how to write about this bug in shortly.
`Combined Language Crash Bug Fix`? `Bug Fix for Korean`? sorry for unclear :(

**Comment by kuler90** [comment]
I think comment `// Fix for Korean language - https://github.com/kuler90/RKTagsView/pull/19` alongside `if` will be good. Update the PR and I merge it.

**Comment by pilgwon** [comment]
OK! I modified the code :)

**Comment by pilgwon** [comment]
Thanks! 👍

**Comment by kuler90** [comment]
One more thing, this changes applied to the same version of pods (1.3.0) so you need run `pod cache clean --all` before `pod install`.

**Comment by pilgwon** [comment]
👍 💯 Got it

**Pull request merged**
